import * as simpleIcons from 'simple-icons';
// @ts-ignore
import * as technologyIcons from '../../dist/index';
import * as fs from 'fs';

let content = `<!--
This file is automatically generated. If you want to change something, please
update the script at tools/generate_slugs.ts.
-->

# Simple Icons slugs

This list contains all of the icons supported by Simple Icons. This file is a copy of
[slugs.md](https://github.com/simple-icons/simple-icons/blob/develop/slugs.md) from Simple Icons repo but,
with shields generated by TechnologyIcons.

| Brand name | Brand slug | Shield |
| :--------- | :--------- | :----: |
`;

for (const iconSlug in simpleIcons) {
	const icon = simpleIcons.get(iconSlug);
	const shield = technologyIcons.get(iconSlug, 'MARKDOWN');
	const brandName = icon.title;
	content += `| \`${brandName}\` | \`${iconSlug}\` | ${shield} |\n`;
}

fs.writeFileSync('slugs.md', content);
